services:
  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    env_file: .env
    secrets:
      - db_password
      - db_root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inception
    restart: on-failure

  nginx:
    build:
      context: ./requirements/nginx
    image: nginx
    container_name: nginx
    env_file: .env
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    ports:
      - "443:443"
    restart: on-failure

  wordpress:
    build:
      context: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    env_file: .env
    secrets:
      - db_password
      - credentials
    volumes:
      - wp_data:/var/www/html
    networks:
      - inception
    depends_on:
      - mariadb
      - redis
    restart: on-failure

  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    restart: on-failure
    ports:
      - "8080:8080"
    networks:
      - inception
    depends_on:
      - mariadb

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis
    container_name: redis
    volumes:
      - rds_data:/data
    restart: on-failure
    networks:
      - inception
    ports:
      - "6379:6379"

  website:
    build:
      context: ./requirements/bonus/website
    image: website
    container_name: website
    restart: on-failure
    networks:
      - inception
    ports:
      - "4242:4242"


volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
  wp_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  rds_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/redis


networks:
  inception:
    driver: bridge


secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  credentials:
    file: ../secrets/credentials.txt
