FROM debian:bookworm

RUN apt-get update && apt-get install -y php8.2-redis redis-server

COPY tools/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]